kind: Service
apiVersion: v1
metadata:
  name: greet-blue
  namespace: greet-ns
  labels:
    app: greet-blue
    role: blue
spec:
  type: LoadBalancer
  selector:
    app: greet-blue
    role: blue
  ports:
    - port: 80
      targetPort: 8080
